import { ActionItem, StakeholderRole, TrackingLevel, ExecutiveOffice, InsightCategory } from './types';

export const MOCK_MEETINGS = [
  {
    id: 'm1',
    title: 'Board Meeting #4',
    date: '2026-06-16',
    duration: '1h 30m',
    platform: 'Google Meet',
    status: 'Processed',
    folderPath: '/Board/2026/Q2',
    participant: 'Substitute Name',
    place: 'Online',
  },
  {
    id: 'm2',
    title: 'Board Meeting #3',
    date: '2026-03-16',
    duration: '45m',
    platform: 'Microsoft Teams',
    status: 'Processed',
    folderPath: '/Board/2026/Q1',
    participant: '',
    place: 'SA, Australia',
  },
  {
    id: 'm3',
    title: 'Board Meeting #2',
    date: '2025-12-16',
    duration: '30m',
    platform: 'Zoom',
    status: 'Processing',
    folderPath: '/Board/2025/Q4',
    participant: '',
    place: 'Online',
  },
  {
    id: 'm4',
    title: 'Board Meeting #1',
    date: '2025-09-16',
    duration: '1h',
    platform: 'Google Meet',
    status: 'Pending',
    folderPath: '/Board/2025/Q3',
    participant: '',
    place: 'SA, Australia',
  },
] as const;

export const MOCK_ACTIONS: ActionItem[] = [
  // ── Flagship PPTX example (Board Meeting #4) ──
  {
    id: 'a0',
    title: 'Reduce Operational Expenditure',
    description: 'Reduce operational expenditure across non-core business units.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.BOARD_ACTION,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm1',
    dueDate: '2026-07-12',
    chainOfThought: 'Comment # 1\nComment # 2',
    offices: [ExecutiveOffice.CEO, ExecutiveOffice.CFO],
    category: InsightCategory.ACTION,
  },

  // ── Board Actions (6) ──
  {
    id: 'a1',
    title: 'Approve FY27 Budget Allocation',
    description: 'Finalize board-level approval for the infrastructure transformation budget.',
    role: StakeholderRole.LEADER,
    level: TrackingLevel.BOARD_ACTION,
    status: 'Completed',
    priority: 'High',
    sourceMeetingId: 'm1',
    dueDate: '2026-05-15',
    chainOfThought: 'Derived from Board consensus at 14:20 marker regarding capital expenditure limits.',
    offices: [ExecutiveOffice.BOARD],
    category: InsightCategory.ACTION
  },
  {
    id: 'a10',
    title: 'Executive Dashboard Enhancement',
    description: 'Add advanced analytics and reporting capabilities to the executive dashboard.',
    role: StakeholderRole.SUPPORTER,
    level: TrackingLevel.PROJECT,
    status: 'In Progress',
    priority: 'Medium',
    sourceMeetingId: 'm2',
    dueDate: '2026-06-08',
    chainOfThought: 'CTO proposed dashboard enhancements during tech leadership review.',
    offices: [ExecutiveOffice.BOARD],
    category: InsightCategory.ACTION
  },
  {
    id: 'a19',
    title: 'Review Q3 Strategic Objectives',
    description: 'Board to review and approve Q3 strategic objectives and key results.',
    role: StakeholderRole.LEADER,
    level: TrackingLevel.BOARD_ACTION,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm1',
    dueDate: '2026-06-30',
    chainOfThought: 'Board committee requested quarterly objective review during governance session.',
    offices: [ExecutiveOffice.BOARD],
    category: InsightCategory.ACTION
  },
  {
    id: 'a20',
    title: 'Approve New Entity Formation',
    description: 'Review and approve the legal structure for the new subsidiary entity.',
    role: StakeholderRole.LEADER,
    level: TrackingLevel.BOARD_ACTION,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm1',
    dueDate: '2026-07-15',
    chainOfThought: 'Legal team presented entity structure options during board strategy session.',
    offices: [ExecutiveOffice.BOARD],
    category: InsightCategory.ACTION
  },
  {
    id: 'a21',
    title: 'Board Governance Policy Update',
    description: 'Update board governance policies to align with ASX corporate governance guidelines.',
    role: StakeholderRole.LEADER,
    level: TrackingLevel.BOARD_ACTION,
    status: 'In Progress',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    dueDate: '2026-08-01',
    chainOfThought: 'Governance committee recommended policy updates during compliance review.',
    offices: [ExecutiveOffice.BOARD],
    category: InsightCategory.ACTION
  },
  {
    id: 'a22',
    title: 'Executive Succession Planning',
    description: 'Develop executive succession plan for key leadership positions.',
    role: StakeholderRole.LEADER,
    level: TrackingLevel.BOARD_ACTION,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    dueDate: '2026-09-01',
    chainOfThought: 'Board identified succession planning as critical risk mitigation during governance review.',
    offices: [ExecutiveOffice.BOARD],
    category: InsightCategory.ACTION
  },

  // ── Board Risks (3) ──
  {
    id: 'a11',
    title: 'Risk Management Framework Update',
    description: 'Update enterprise risk management framework to include emerging digital risks.',
    role: StakeholderRole.LEADER,
    level: TrackingLevel.VISION,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    dueDate: '2026-05-29',
    chainOfThought: 'Board requested risk framework update during governance meeting.',
    offices: [ExecutiveOffice.BOARD],
    category: InsightCategory.RISK
  },
  {
    id: 'a23',
    title: 'Geopolitical Risk Assessment',
    description: 'Assess exposure to geopolitical risks across Asia-Pacific operations.',
    role: StakeholderRole.LEADER,
    level: TrackingLevel.BOARD_ACTION,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm1',
    dueDate: '2026-06-20',
    chainOfThought: 'Board risk committee flagged Asia-Pacific geopolitical tensions as emerging concern.',
    offices: [ExecutiveOffice.BOARD],
    category: InsightCategory.RISK
  },
  {
    id: 'a24',
    title: 'Cybersecurity Threat Landscape Review',
    description: 'Review evolving cybersecurity threat landscape and board-level risk posture.',
    role: StakeholderRole.LEADER,
    level: TrackingLevel.BOARD_ACTION,
    status: 'In Progress',
    priority: 'High',
    sourceMeetingId: 'm1',
    dueDate: '2026-06-25',
    chainOfThought: 'CISO presented threat landscape analysis during board security briefing.',
    offices: [ExecutiveOffice.BOARD],
    category: InsightCategory.RISK
  },

  // ── Board Issues (2) ──
  {
    id: 'a17',
    title: 'Legacy System Retirement',
    description: 'Plan and execute retirement of legacy systems to reduce maintenance overhead.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    dueDate: '2026-05-20',
    chainOfThought: 'Board requested legacy system retirement during governance review.',
    offices: [ExecutiveOffice.BOARD],
    category: InsightCategory.ISSUE
  },
  {
    id: 'a25',
    title: 'Compliance Gap in Data Retention',
    description: 'Address compliance gaps in data retention policies across business units.',
    role: StakeholderRole.LEADER,
    level: TrackingLevel.BOARD_ACTION,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm1',
    dueDate: '2026-06-15',
    chainOfThought: 'Regulatory audit identified data retention compliance gaps needing board attention.',
    offices: [ExecutiveOffice.BOARD],
    category: InsightCategory.ISSUE
  },

  // ── CEO Items (2) ──
  {
    id: 'a2',
    title: 'CEO Vision: Customer First 2.0',
    description: 'Draft the vision document for the new customer experience transformation.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.VISION,
    status: 'In Progress',
    priority: 'High',
    sourceMeetingId: 'm1',
    dueDate: '2026-06-01',
    chainOfThought: 'CEO emphasised "radical simplicity" multiple times during the UX segment.',
    offices: [ExecutiveOffice.CEO],
    category: InsightCategory.CEO_ITEM
  },
  {
    id: 'a15',
    title: 'Product Innovation Strategy',
    description: 'Develop new product innovation strategy aligned with market opportunities.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.VISION,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    chainOfThought: 'CEO requested innovation strategy during strategic planning session.',
    offices: [ExecutiveOffice.CEO],
    category: InsightCategory.CEO_ITEM
  },

  // ── CEO Operations (7) ──
  {
    id: 'a26',
    title: 'Operational Efficiency Review',
    description: 'Conduct comprehensive review of operational efficiency across all departments.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.TRANSFORMATION,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm1',
    dueDate: '2026-06-30',
    chainOfThought: 'CEO requested operational efficiency review during strategic planning.',
    offices: [ExecutiveOffice.CEO],
    category: InsightCategory.OPERATIONS
  },
  {
    id: 'a27',
    title: 'Cross-Functional Alignment Initiative',
    description: 'Drive cross-functional alignment between engineering, product, and marketing.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.PROGRAM,
    status: 'In Progress',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    chainOfThought: 'CEO identified silo risks during leadership team alignment session.',
    offices: [ExecutiveOffice.CEO],
    category: InsightCategory.OPERATIONS
  },
  {
    id: 'a28',
    title: 'Talent Acquisition Strategy',
    description: 'Develop strategic hiring plan for key technical and leadership roles.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.PROGRAM,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    dueDate: '2026-07-01',
    chainOfThought: 'CEO highlighted talent gap as critical path item during Q2 planning.',
    offices: [ExecutiveOffice.CEO],
    category: InsightCategory.OPERATIONS
  },
  {
    id: 'a29',
    title: 'Vendor Performance Management',
    description: 'Implement vendor performance management framework for strategic suppliers.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'Low',
    sourceMeetingId: 'm2',
    chainOfThought: 'Operations team identified vendor performance gaps during supply chain review.',
    offices: [ExecutiveOffice.CEO],
    category: InsightCategory.OPERATIONS
  },
  {
    id: 'a30',
    title: 'Internal Communications Overhaul',
    description: 'Revamp internal communications strategy for better organisational transparency.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'Low',
    sourceMeetingId: 'm1',
    chainOfThought: 'Employee engagement survey revealed communications gaps needing CEO attention.',
    offices: [ExecutiveOffice.CEO],
    category: InsightCategory.OPERATIONS
  },
  {
    id: 'a31',
    title: 'Board Reporting Automation',
    description: 'Automate board reporting processes to reduce manual preparation overhead.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.PROJECT,
    status: 'In Progress',
    priority: 'Medium',
    sourceMeetingId: 'm2',
    dueDate: '2026-07-15',
    chainOfThought: 'CEO identified reporting inefficiencies during board preparation cycle.',
    offices: [ExecutiveOffice.CEO],
    category: InsightCategory.OPERATIONS
  },
  {
    id: 'a32',
    title: 'OKR Setting for H2 2026',
    description: 'Facilitate company-wide OKR setting process for second half of 2026.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.PROGRAM,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    dueDate: '2026-06-20',
    chainOfThought: 'CEO directed OKR alignment to ensure strategic coherence across all departments.',
    offices: [ExecutiveOffice.CEO],
    category: InsightCategory.OPERATIONS
  },

  // ── CFO Items (5) ──
  {
    id: 'a3',
    title: 'CFO Compliance Reporting',
    description: 'Ensure all transformation programs are compliant with new tax regulations.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.TRANSFORMATION,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    dueDate: '2026-07-01',
    chainOfThought: 'CFO highlighted tax compliance risks during the budget review.',
    offices: [ExecutiveOffice.CFO],
    category: InsightCategory.CFO_ITEM
  },
  {
    id: 'a14',
    title: 'Financial Reporting Automation',
    description: 'Automate financial reporting processes to reduce manual errors and improve accuracy.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    dueDate: '2026-05-25',
    chainOfThought: 'CFO proposed automation initiatives during finance operations review.',
    offices: [ExecutiveOffice.CFO],
    category: InsightCategory.CFO_ITEM
  },
  {
    id: 'a33',
    title: 'Capital Expenditure Optimisation',
    description: 'Optimise capital expenditure allocation across transformation programmes.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.PROGRAM,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm1',
    dueDate: '2026-06-30',
    chainOfThought: 'CFO identified capex optimisation opportunities during budget planning.',
    offices: [ExecutiveOffice.CFO],
    category: InsightCategory.CFO_ITEM
  },
  {
    id: 'a34',
    title: 'Revenue Forecasting Model Update',
    description: 'Update revenue forecasting model to incorporate new market segment data.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.PROJECT,
    status: 'In Progress',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    dueDate: '2026-06-15',
    chainOfThought: 'CFO requested forecast model updates during quarterly business review.',
    offices: [ExecutiveOffice.CFO],
    category: InsightCategory.CFO_ITEM
  },
  {
    id: 'a35',
    title: 'Cost Reduction Programme',
    description: 'Identify and implement cost reduction measures across non-core operations.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.PROGRAM,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm1',
    dueDate: '2026-07-01',
    chainOfThought: 'CFO identified margin pressure requiring cost reduction initiatives.',
    offices: [ExecutiveOffice.CFO],
    category: InsightCategory.CFO_ITEM
  },

  // ── CFO Operations (7) ──
  {
    id: 'a36',
    title: 'Accounts Payable Process Optimisation',
    description: 'Streamline accounts payable processes to reduce payment cycle times.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.PROJECT,
    status: 'In Progress',
    priority: 'Medium',
    sourceMeetingId: 'm2',
    dueDate: '2026-06-20',
    chainOfThought: 'Finance team identified AP process inefficiencies during operational review.',
    offices: [ExecutiveOffice.CFO],
    category: InsightCategory.OPERATIONS
  },
  {
    id: 'a37',
    title: 'Treasury Management Enhancement',
    description: 'Enhance treasury management systems for better cash flow visibility.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm1',
    dueDate: '2026-07-01',
    chainOfThought: 'CFO identified cash flow visibility gaps during treasury review.',
    offices: [ExecutiveOffice.CFO],
    category: InsightCategory.OPERATIONS
  },
  {
    id: 'a38',
    title: 'Procurement Cost Analysis',
    description: 'Conduct comprehensive procurement cost analysis across all vendor categories.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm2',
    dueDate: '2026-06-25',
    chainOfThought: 'Procurement team flagged cost variances needing CFO review.',
    offices: [ExecutiveOffice.CFO],
    category: InsightCategory.OPERATIONS
  },
  {
    id: 'a39',
    title: 'Financial Controls Audit',
    description: 'Execute internal audit of financial controls across all business units.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm3',
    dueDate: '2026-06-30',
    chainOfThought: 'Internal audit committee recommended financial controls review.',
    offices: [ExecutiveOffice.CFO],
    category: InsightCategory.OPERATIONS
  },
  {
    id: 'a40',
    title: 'Budget Variance Analysis',
    description: 'Perform detailed budget variance analysis for Q2 2026 actuals vs plan.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.PROJECT,
    status: 'In Progress',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    dueDate: '2026-06-10',
    chainOfThought: 'CFO requested variance analysis during monthly financial review.',
    offices: [ExecutiveOffice.CFO],
    category: InsightCategory.OPERATIONS
  },
  {
    id: 'a41',
    title: 'Invoice Processing Digitisation',
    description: 'Digitise invoice processing workflows to reduce manual handling costs.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'Low',
    sourceMeetingId: 'm2',
    dueDate: '2026-08-01',
    chainOfThought: 'Finance operations team identified digitisation opportunity during process mapping.',
    offices: [ExecutiveOffice.CFO],
    category: InsightCategory.OPERATIONS
  },
  {
    id: 'a42',
    title: 'Tax Compliance Calendar Implementation',
    description: 'Implement automated tax compliance calendar for all jurisdictional filings.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm3',
    dueDate: '2026-07-15',
    chainOfThought: 'Tax team identified filing deadline risks needing systematic tracking.',
    offices: [ExecutiveOffice.CFO],
    category: InsightCategory.OPERATIONS
  },

  // ── Shared / Cross-office items ──
  {
    id: 'a6',
    title: 'Customer Experience Platform Launch',
    description: 'Implement the new customer experience platform across all touchpoints.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.PROGRAM,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    dueDate: '2026-05-22',
    chainOfThought: 'CEO announced platform as strategic priority during Q2 planning.',
    offices: [ExecutiveOffice.CEO, ExecutiveOffice.CMO],
    category: InsightCategory.PROGRAM
  },
  {
    id: 'a12',
    title: 'Supply Chain Digital Transformation',
    description: 'Digitize supply chain operations for improved visibility and efficiency.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.PROGRAM,
    status: 'Pending',
    priority: 'Low',
    sourceMeetingId: 'm1',
    chainOfThought: 'CFO identified supply chain inefficiencies during budget review.',
    offices: [ExecutiveOffice.CFO, ExecutiveOffice.COO],
    category: InsightCategory.PROGRAM
  },
  {
    id: 'a18',
    title: 'Data Governance Framework',
    description: 'Establish comprehensive data governance framework for regulatory compliance.',
    role: StakeholderRole.SUPPORTER,
    level: TrackingLevel.PROGRAM,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm2',
    chainOfThought: 'CFO emphasised need for data governance during financial reporting review.',
    offices: [ExecutiveOffice.CFO, ExecutiveOffice.CIO],
    category: InsightCategory.ISSUE
  },
  {
    id: 'a9',
    title: 'Australian privacy compliance review for transcript handling',
    description: 'Conduct comprehensive review of transcript handling practices for Australian privacy law compliance.',
    role: StakeholderRole.INFORMED,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm1',
    chainOfThought: 'Regulatory team identified privacy compliance gaps during transcript processing audit.',
    offices: [ExecutiveOffice.CEO, ExecutiveOffice.CIO],
    category: InsightCategory.REGULATORY
  },
  {
    id: 'a4',
    title: 'Legacy DB Migration Program',
    description: 'Oversee the migration of legacy SQL clusters to AWS RDS.',
    role: StakeholderRole.INFORMED,
    level: TrackingLevel.PROGRAM,
    status: 'In Progress',
    priority: 'Medium',
    sourceMeetingId: 'm2',
    chainOfThought: 'CIO committed to modernize infrastructure during the tech sync.',
    offices: [ExecutiveOffice.CIO],
    category: InsightCategory.PROGRAM
  },
  {
    id: 'a7',
    title: 'Cloud Migration Strategy',
    description: 'Develop comprehensive cloud migration roadmap for all legacy systems.',
    role: StakeholderRole.LEADER,
    level: TrackingLevel.TRANSFORMATION,
    status: 'In Progress',
    priority: 'High',
    sourceMeetingId: 'm2',
    dueDate: '2026-06-15',
    chainOfThought: 'CIO presented transformation agenda during infrastructure sync.',
    offices: [ExecutiveOffice.CIO, ExecutiveOffice.CTO],
    category: InsightCategory.PROGRAM
  },
  {
    id: 'a8',
    title: 'Data Privacy Framework Implementation',
    description: 'Establish comprehensive data privacy controls across all business units.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm3',
    chainOfThought: 'CISO identified privacy gaps during security review.',
    offices: [ExecutiveOffice.CIO, ExecutiveOffice.CISO],
    category: InsightCategory.RISK
  },
  {
    id: 'a5',
    title: 'IAM Policy Audit',
    description: 'Execute deep audit of all identity access management policies across GCP.',
    role: StakeholderRole.SUPPORTER,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm3',
    chainOfThought: 'CISO raised security concerns about current IAM configuration.',
    offices: [ExecutiveOffice.CISO],
    category: InsightCategory.RISK
  },
  {
    id: 'a13',
    title: 'Cybersecurity Incident Response Plan',
    description: 'Develop comprehensive incident response plan for cybersecurity threats.',
    role: StakeholderRole.SUPPORTER,
    level: TrackingLevel.PROJECT,
    status: 'In Progress',
    priority: 'High',
    sourceMeetingId: 'm2',
    dueDate: '2026-06-12',
    chainOfThought: 'CISO mandated incident response plan after security audit findings.',
    offices: [ExecutiveOffice.CISO, ExecutiveOffice.CTO],
    category: InsightCategory.RISK
  },
  {
    id: 'a16',
    title: 'IT Infrastructure Modernization',
    description: 'Modernize IT infrastructure to support digital transformation initiatives.',
    role: StakeholderRole.INFORMED,
    level: TrackingLevel.TRANSFORMATION,
    status: 'Pending',
    priority: 'Low',
    sourceMeetingId: 'm2',
    chainOfThought: 'CIO presented infrastructure roadmap during technology leadership meeting.',
    offices: [ExecutiveOffice.CIO, ExecutiveOffice.CTO, ExecutiveOffice.COO],
    category: InsightCategory.PROGRAM
  }
];
