import { ActionItem, StakeholderRole, TrackingLevel, ExecutiveOffice, InsightCategory } from './types';

export const MOCK_MEETINGS = [
  {
    id: 'm1',
    title: 'Q2 Strategic Planning - Board Review',
    date: '2026-04-20',
    duration: '1h 30m',
    platform: 'Zoom',
    status: 'Processed',
    folderPath: '/Archive/Strategic/2026/Q2'
  },
  {
    id: 'm2',
    title: 'Infra Transformation Sync',
    date: '2026-04-22',
    duration: '45m',
    platform: 'Microsoft Teams',
    status: 'Processed',
    folderPath: '/Teams/Transformations'
  },
  {
    id: 'm3',
    title: 'CISO Weekly Security Update',
    date: '2026-04-25',
    duration: '30m',
    platform: 'Google Meet',
    status: 'Processing',
    folderPath: '/Google/Security'
  }
] as const;

export const MOCK_ACTIONS: ActionItem[] = [
  {
    id: 'a1',
    title: 'Approve FY27 Budget Allocation',
    description: 'Finalize board-level approval for the infrastructure transformation budget.',
    role: StakeholderRole.LEADER,
    level: TrackingLevel.BOARD_ACTION,
    status: 'Completed',
    priority: 'High',
    sourceMeetingId: 'm1',
    dueDate: '2026-05-15',
    chainOfThought: 'Derived from Board consensus at 14:20 marker regarding capital expenditure limits.',
    offices: [ExecutiveOffice.BOARD],
    category: InsightCategory.ACTION
  },
  {
    id: 'a2',
    title: 'CEO Vision: Customer First 2.0',
    description: 'Draft the vision document for the new customer experience transformation.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.VISION,
    status: 'In Progress',
    priority: 'High',
    sourceMeetingId: 'm1',
    dueDate: '2026-06-01',
    chainOfThought: 'CEO emphasized "radical simplicity" multiple times during the UX segment.',
    offices: [ExecutiveOffice.CEO],
    category: InsightCategory.MISSION
  },
  {
    id: 'a3',
    title: 'CFO Compliance Reporting',
    description: 'Ensure all transformation programs are compliant with new tax regulations.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.TRANSFORMATION,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    dueDate: '2026-07-01',
    chainOfThought: 'CFO highlighted tax compliance risks during the budget review.',
    offices: [ExecutiveOffice.CFO],
    category: InsightCategory.REGULATORY
  },
  {
    id: 'a4',
    title: 'Legacy DB Migration Program',
    description: 'Oversee the migration of legacy SQL clusters to AWS RDS.',
    role: StakeholderRole.INFORMED,
    level: TrackingLevel.PROGRAM,
    status: 'In Progress',
    priority: 'Medium',
    sourceMeetingId: 'm2',
    chainOfThought: 'CIO committed to modernize infrastructure during the tech sync.',
    offices: [ExecutiveOffice.CIO],
    category: InsightCategory.PROGRAM
  },
  {
    id: 'a5',
    title: 'IAM Policy Audit',
    description: 'Execute deep audit of all identity access management policies across GCP.',
    role: StakeholderRole.SUPPORTER,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm3',
    chainOfThought: 'CISO raised security concerns about current IAM configuration.',
    offices: [ExecutiveOffice.CISO],
    category: InsightCategory.RISK
  },
  {
    id: 'a6',
    title: 'Customer Experience Platform Launch',
    description: 'Implement the new customer experience platform across all touchpoints.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.PROGRAM,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    dueDate: '2026-05-22',
    chainOfThought: 'CEO announced platform as strategic priority during Q2 planning.',
    offices: [ExecutiveOffice.CEO, ExecutiveOffice.CMO],
    category: InsightCategory.PROGRAM
  },
  {
    id: 'a7',
    title: 'Cloud Migration Strategy',
    description: 'Develop comprehensive cloud migration roadmap for all legacy systems.',
    role: StakeholderRole.LEADER,
    level: TrackingLevel.TRANSFORMATION,
    status: 'In Progress',
    priority: 'High',
    sourceMeetingId: 'm2',
    dueDate: '2026-06-15',
    chainOfThought: 'CIO presented transformation agenda during infrastructure sync.',
    offices: [ExecutiveOffice.CIO, ExecutiveOffice.CTO],
    category: InsightCategory.PROGRAM
  },
  {
    id: 'a8',
    title: 'Data Privacy Framework Implementation',
    description: 'Establish comprehensive data privacy controls across all business units.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm3',
    chainOfThought: 'CISO identified privacy gaps during security review.',
    offices: [ExecutiveOffice.CIO, ExecutiveOffice.CISO],
    category: InsightCategory.RISK
  },
  {
    id: 'a9',
    title: 'Australian privacy compliance review for transcript handling',
    description: 'Conduct comprehensive review of transcript handling practices for Australian privacy law compliance.',
    role: StakeholderRole.INFORMED,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm1',
    chainOfThought: 'Regulatory team identified privacy compliance gaps during transcript processing audit.',
    offices: [ExecutiveOffice.CEO, ExecutiveOffice.CIO],
    category: InsightCategory.REGULATORY
  },
  {
    id: 'a10',
    title: 'Executive Dashboard Enhancement',
    description: 'Add advanced analytics and reporting capabilities to the executive dashboard.',
    role: StakeholderRole.SUPPORTER,
    level: TrackingLevel.PROJECT,
    status: 'In Progress',
    priority: 'Medium',
    sourceMeetingId: 'm2',
    dueDate: '2026-06-08',
    chainOfThought: 'CTO proposed dashboard enhancements during tech leadership review.',
    offices: [ExecutiveOffice.CTO, ExecutiveOffice.COO],
    category: InsightCategory.ACTION
  },
  {
    id: 'a11',
    title: 'Risk Management Framework Update',
    description: 'Update enterprise risk management framework to include emerging digital risks.',
    role: StakeholderRole.LEADER,
    level: TrackingLevel.VISION,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm3',
    dueDate: '2026-05-29',
    chainOfThought: 'Board requested risk framework update during governance meeting.',
    offices: [ExecutiveOffice.BOARD, ExecutiveOffice.CEO],
    category: InsightCategory.RISK
  },
  {
    id: 'a12',
    title: 'Supply Chain Digital Transformation',
    description: 'Digitize supply chain operations for improved visibility and efficiency.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.PROGRAM,
    status: 'Pending',
    priority: 'Low',
    sourceMeetingId: 'm1',
    chainOfThought: 'CFO identified supply chain inefficiencies during budget review.',
    offices: [ExecutiveOffice.CFO, ExecutiveOffice.COO],
    category: InsightCategory.PROGRAM
  },
  {
    id: 'a13',
    title: 'Cybersecurity Incident Response Plan',
    description: 'Develop comprehensive incident response plan for cybersecurity threats.',
    role: StakeholderRole.SUPPORTER,
    level: TrackingLevel.PROJECT,
    status: 'In Progress',
    priority: 'High',
    sourceMeetingId: 'm2',
    dueDate: '2026-06-12',
    chainOfThought: 'CISO mandated incident response plan after security audit findings.',
    offices: [ExecutiveOffice.CISO, ExecutiveOffice.CTO],
    category: InsightCategory.RISK
  },
  {
    id: 'a14',
    title: 'Financial Reporting Automation',
    description: 'Automate financial reporting processes to reduce manual errors and improve accuracy.',
    role: StakeholderRole.CONTRIBUTOR,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm3',
    dueDate: '2026-05-25',
    chainOfThought: 'CFO proposed automation initiatives during finance operations review.',
    offices: [ExecutiveOffice.CFO],
    category: InsightCategory.ACTION
  },
  {
    id: 'a15',
    title: 'Product Innovation Strategy',
    description: 'Develop new product innovation strategy aligned with market opportunities.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.VISION,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    chainOfThought: 'CEO requested innovation strategy during strategic planning session.',
    offices: [ExecutiveOffice.CEO, ExecutiveOffice.CMO],
    category: InsightCategory.MISSION
  },
  {
    id: 'a16',
    title: 'IT Infrastructure Modernization',
    description: 'Modernize IT infrastructure to support digital transformation initiatives.',
    role: StakeholderRole.INFORMED,
    level: TrackingLevel.TRANSFORMATION,
    status: 'Pending',
    priority: 'Low',
    sourceMeetingId: 'm2',
    chainOfThought: 'CIO presented infrastructure roadmap during technology leadership meeting.',
    offices: [ExecutiveOffice.CIO, ExecutiveOffice.CTO, ExecutiveOffice.COO],
    category: InsightCategory.PROGRAM
  },
  {
    id: 'a17',
    title: 'Legacy System Retirement',
    description: 'Plan and execute retirement of legacy systems to reduce maintenance overhead.',
    role: StakeholderRole.DRIVER,
    level: TrackingLevel.PROJECT,
    status: 'Pending',
    priority: 'Medium',
    sourceMeetingId: 'm1',
    dueDate: '2026-05-20',
    chainOfThought: 'Board requested legacy system retirement during governance review.',
    offices: [ExecutiveOffice.BOARD, ExecutiveOffice.CIO],
    category: InsightCategory.ISSUE
  },
  {
    id: 'a18',
    title: 'Data Governance Framework',
    description: 'Establish comprehensive data governance framework for regulatory compliance.',
    role: StakeholderRole.SUPPORTER,
    level: TrackingLevel.PROGRAM,
    status: 'Pending',
    priority: 'High',
    sourceMeetingId: 'm2',
    chainOfThought: 'CFO emphasized need for data governance during financial reporting review.',
    offices: [ExecutiveOffice.CFO, ExecutiveOffice.CIO],
    category: InsightCategory.ISSUE
  }
];
